# Normal Options
arrowParens: "always"
bracketSpacing: false
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "css"
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 99
quoteProps: "as-needed"
semi: false
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false

# JSDoc plugin
jsdocSpaces: 1
jsdocDescriptionWithDot: false
jsdocDescriptionTag: false
jsdocVerticalAlignment: false
jsdocKeepUnParseAbleExampleIndent: false
jsdocSingleLineComment: false
tsdoc: true

svelteSortOrder: "options-styles-scripts-markup"
svelteStrictMode: false
svelteBracketNewLine: false
svelteAllowShorthand: true
svelteIndentScriptAndStyle: true

overrides:
  - files:
      - "*.html"
      - "*.yml"
      - "*.yaml"
      - "*.json"
      - "*.css"
      - "*.scss"
    options:
      tabWidth: 2
