name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 

      - name: install deps
        run: yarn install --frozen-lockfile

      - name: lint
        run: bash lint.sh

      - name: build
        run: yarn build

      - name: upload JS
        uses: actions/upload-artifact@v2
        with:
          name: js
          path: js

      - name: upload CSS
        uses: actions/upload-artifact@v2
        with:
          name: css
          path: css

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download JS
        uses: actions/download-artifact@v2
        with:
          name: js
          path: js

      - name: Download CSS
        uses: actions/download-artifact@v2
        with:
          name: css
          path: css

      - name: Add and Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: "js css"
          force: true
          signoff: true
          message: "Pages deployment for commit $commit_hash"
          ref: "gh-pages"
        env:
          commit_hash: "$(git rev-parse HEAD)"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
