name: Build

on: [pull_request, push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: yarn install --frozen-lockfile

      - name: lint
        run: bash lint.sh

      - name: build
        run: yarn build
