name: Build

on: [pull_request, push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: typecheck
        run: pnpm tsc --noEmit

      - name: lint
        run: pnpm lint

      - name: prettier check
        run: pnpm prettier . --check

      - name: build rollup plugins
        run: pnpm build --filter rollup-plugins

      - name: build
        run: pnpm build
