name: Build

on: [pull_request, push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.11

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: typecheck
        run: pnpm tsc --noEmit

      - name: lint
        run: pnpm lint

      - name: prettier check
        run: pnpm prettier . --check

      - name: build rollup plugins
        run: pnpm run -r --filter rollup-plugins build

      - name: build
        run: pnpm build
